# Generated by Django 4.2.9 on 2024-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stageId', models.AutoField(primary_key=True, serialize=False)),
                ('stageName', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
