# Generated by Django 4.2.9 on 2024-05-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0005_alter_dependency_page'),
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='dependencyIdFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependency.dependency'),
        ),
    ]
