# Generated by Django 4.2.9 on 2024-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('dependencyId', models.AutoField(primary_key=True, serialize=False)),
                ('dependencyName', models.CharField(max_length=128, unique=True)),
                ('owner', models.CharField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('logo', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dependency')),
            ],
        ),
    ]
