# Generated by Django 4.2.9 on 2024-05-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='image',
        ),
        migrations.AlterField(
            model_name='dependency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dependency'),
        ),
    ]
