# Generated by Django 4.2.9 on 2024-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0002_remove_dependency_image_alter_dependency_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='owner',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
