# Generated by Django 4.2.9 on 2024-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0003_alter_dependency_address_alter_dependency_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='page',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
