# Generated by Django 4.2.9 on 2024-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0004_dependency_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='page',
            field=models.CharField(max_length=128),
        ),
    ]
