# Generated by Django 4.2.9 on 2024-04-30 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
        ('range', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteId', models.AutoField(primary_key=True, serialize=False)),
                ('voteDate', models.DateTimeField(auto_now=True)),
                ('revocationStatus', models.BooleanField(blank=True, default=False, null=True)),
                ('empCandidateIdFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Candidate', to=settings.AUTH_USER_MODEL)),
                ('empVoterIdFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Voter', to=settings.AUTH_USER_MODEL)),
                ('rangeIdFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='range.range')),
                ('stageIdFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stage.stage')),
            ],
        ),
    ]
