# Generated by Django 4.2.9 on 2024-05-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voteDate',
            field=models.DateTimeField(),
        ),
    ]
