# Generated by Django 4.2.9 on 2024-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_vote_votedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voteDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
