# Generated by Django 4.2.9 on 2024-05-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_vote_votedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='period',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
