# Generated by Django 4.2.9 on 2024-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgetPasswordRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpasswordrequest',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
