# Generated by Django 4.2.9 on 2024-08-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgetPasswordRequest', '0002_alter_forgetpasswordrequest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpasswordrequest',
            name='useCode',
            field=models.BooleanField(default=False),
        ),
    ]
