# Generated by Django 4.2.9 on 2024-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('rangeId', models.AutoField(primary_key=True, serialize=False)),
                ('rangeName', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
