# Generated by Django 4.2.9 on 2024-05-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dependencyId',
            new_name='dependencyIdFK',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rankIdFk',
            new_name='rankIdFK',
        ),
    ]
